//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SantaMesa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public int id_Administrador { get; set; }
        public string nombres { get; set; }
        public string tenefono { get; set; }
        public string email { get; set; }
        public string direccion { get; set; }
        public string dni { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
